import { ImagingType } from "./types";

const imagingSeed: ImagingType[] = [
	{
		study: "CT Abdomen w/ Contrast",
		imagingId: "IMG-101",
		modality: "CT",
		region: "Abdomen",
		impression: "Suspicious liver lesion",
		orderedAtLabel: "1st Mar 2026, 2:30 PM",
		orderedAtSortValue: "2026-03-01T14:30:00.000Z",
		status: "Completed",
	},
	{
		study: "Chest X-ray",
		imagingId: "IMG-101",
		modality: "X-ray",
		region: "Chest",
		impression: "-",
		orderedAtLabel: "1st Mar 2026, 2:30 PM",
		orderedAtSortValue: "2026-03-01T14:30:00.000Z",
		status: "Pending",
	},
	{
		study: "Obstetric Ultrasound",
		imagingId: "IMG-101",
		modality: "Ultrasound",
		region: "Pelvis",
		impression: "Fetal heartbeat detected",
		orderedAtLabel: "1st Mar 2026, 2:30 PM",
		orderedAtSortValue: "2026-03-01T14:30:00.000Z",
		status: "Completed",
	},
	{
		study: "Brain MRI",
		imagingId: "IMG-101",
		modality: "MRI",
		region: "Brain",
		impression: "-",
		orderedAtLabel: "1st Mar 2026, 2:30 PM",
		orderedAtSortValue: "2026-03-01T14:30:00.000Z",
		status: "Cancelled",
	},
	{
		study: "CT Head",
		imagingId: "IMG-101",
		modality: "CT",
		region: "Head",
		impression: "No intracranial hemorrhage",
		orderedAtLabel: "1st Mar 2026, 2:30 PM",
		orderedAtSortValue: "2026-03-01T14:30:00.000Z",
		status: "Completed",
	},
	{
		study: "Knee X-ray",
		imagingId: "IMG-101",
		modality: "X-ray",
		region: "Knee",
		impression: "-",
		orderedAtLabel: "1st Mar 2026, 2:30 PM",
		orderedAtSortValue: "2026-03-01T14:30:00.000Z",
		status: "Pending",
	},
	{
		study: "Chest CT",
		imagingId: "IMG-101",
		modality: "CT",
		region: "Chest",
		impression: "Pulmonary nodules detected",
		orderedAtLabel: "1st Mar 2026, 2:30 PM",
		orderedAtSortValue: "2026-03-01T14:30:00.000Z",
		status: "Completed",
	},
];

export const imagingStudies: ImagingType[] = Array.from({ length: 6 }, (_, pageIndex) =>
	imagingSeed.map((imagingStudy, itemIndex) => ({
		...imagingStudy,
		imagingId: `IMG-${101 + pageIndex * imagingSeed.length + itemIndex}`,
	})),
).flat();
