import { MedicationType } from "./types";

const medicationSeed: MedicationType[] = [
	{
		medication: "Amoxicillin",
		dose: "500 mg",
		route: "Oral",
		medicationId: "MED 101",
		indication: "Urinary tract infection",
		createdAtLabel: "12th Jan 2026",
		createdAtSortValue: "2026-01-12",
		status: "Active",
	},
	{
		medication: "Metformin",
		dose: "1000 mg",
		route: "Oral",
		medicationId: "MED 101",
		indication: "Type 2 diabetes mellitus",
		createdAtLabel: "3rd Nov 2024",
		createdAtSortValue: "2024-11-03",
		status: "Discontinued",
	},
	{
		medication: "Amlodipine",
		dose: "5 mg",
		route: "Oral",
		medicationId: "MED 101",
		indication: "Hypertension",
		createdAtLabel: "3rd Nov 2024",
		createdAtSortValue: "2024-11-03",
		status: "Completed",
	},
	{
		medication: "Paracetamol",
		dose: "1000 mg",
		route: "Oral",
		medicationId: "MED 101",
		indication: "Pain",
		createdAtLabel: "3rd Nov 2024",
		createdAtSortValue: "2024-11-03",
		status: "Completed",
	},
	{
		medication: "Ceftriaxone",
		dose: "1000 mg",
		route: "Intravenous",
		medicationId: "MED 101",
		indication: "Sepsis",
		createdAtLabel: "3rd Nov 2024",
		createdAtSortValue: "2024-11-03",
		status: "Active",
	},
	{
		medication: "Losartan",
		dose: "50 mg",
		route: "Oral",
		medicationId: "MED 101",
		indication: "Hypertension",
		createdAtLabel: "18th Feb 2025",
		createdAtSortValue: "2025-02-18",
		status: "Active",
	},
];

export const medications: MedicationType[] = Array.from({ length: 7 }, () => medicationSeed).flat();
